name: auth_grace
description: Smart biometric auth with grace period. Skips prompt if phone was recently unlocked.
version: 0.0.6
homepage: https://github.com/vijayrockers/auth_grace

topics:
  - authentication
  - biometrics
  - security
  - local-auth

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.authgrace
        pluginClass: AuthGracePlugin
      ios:
        pluginClass: AuthGracePlugin
